#!/bin/bash
docker compose build --no-cache
docker compose up -d
echo "✅ EXIF API запущен на http://localhost:3000"
echo "📖 Проверка: curl http://localhost:3000/health"
echo "🔧 Проверка exiftool: docker exec -it exif-api exiftool -ver"
echo ""
echo "📋 Типы метаданных: all, exif, iptc, xmp, makernotes, gps, c2pa, jumbf, png"
echo ""
echo "📖 Примеры запросов:"
echo "  Чтение всех метаданных:"
echo "    curl -X POST -F 'file=@photo.jpg' http://localhost:3000/read"
echo ""
echo "  Чтение только EXIF:"
echo "    curl -X POST -F 'file=@photo.jpg' -F 'type=exif' http://localhost:3000/read"
echo ""
echo "  Запись метаданных:"
echo "    curl -X POST -F 'file=@photo.jpg' -F 'metadata={\"Make\":\"Nikon\",\"Model\":\"Z9\"}' http://localhost:3000/write --output test.jpg"
echo ""
echo "  Удаление всех C2PA (AI-подписей):"
echo "    curl -X POST -F 'file=@photo.jpg' -F 'type=c2pa' http://localhost:3000/delete --output clean.jpg"
echo ""
echo "  Удаление всех метаданных:"
echo "    curl -X POST -F 'file=@photo.jpg' http://localhost:3000/delete --output no_metadata.jpg"
